import { test, expect } from '@playwright/test';
import { goToEnvUrl } from '../utils/goToEnvUrl';

test('test', async ({ page }) => {
  await page.goto(goToEnvUrl());
  await page.getByRole('link', { name: 'Ingresar' }).click();
  await page.getByLabel('Email *').click();
  await page.getByLabel('Email *').fill('prestadorwgi@gmail.com');
  await page.getByLabel('Email *').press('Tab');
  await page.getByLabel('Password *').fill('123456');
  await page.getByLabel('Password *').press('Tab');
  await page.getByRole('button', { name: 'Ingresar' }).press('Enter');
  await page.getByRole('button', { name: 'Construir perfil' }).click();
  await page.getByRole('link', { name: 'Servicios ofrecidos' }).click();
  await page.locator('div').filter({ hasText: /^Tus servicios$/ }).getByRole('button').click();
  await page.getByText('Selecciona la especialidad del servicioSelecciona la especialidad del servicio').click();
  await page.getByLabel('Selecciona la especialidad').click();
  await page.getByRole('option', { name: 'Ansiedad' }).click();
  await page.getByLabel('Nombre del servicio').click();
  await page.getByLabel('Nombre del servicio').fill('Terapia DBT');
  await page.getByLabel('Nombre del servicio').press('Tab');
  await page.getByLabel('Descripción del servicio').fill('Terpaia dialectica conductual');
  await page.getByLabel('Descripción del servicio').press('Tab');
  await page.getByLabel('Duración del servicio').press('ArrowDown');
  await page.getByRole('option', { name: 'Selecciona una duración:' }).press('ArrowDown');
  await page.getByRole('option', { name: '15 minutos' }).press('ArrowDown');
  await page.getByRole('option', { name: '30 minutos' }).press('ArrowDown');
  await page.getByRole('option', { name: '45 minutos' }).press('ArrowDown');
  await page.getByRole('option', { name: '1 hora', exact: true }).press('ArrowUp');
  await page.getByRole('option', { name: '45 minutos' }).press('Tab');
  await page.getByText('Duración del servicioDuración').click();
  await page.getByLabel('Duración del servicio').click();
  await page.getByRole('option', { name: '45 minutos' }).click();
  await page.getByPlaceholder('$').click();
  await page.getByPlaceholder('$').fill('40000');
  await page.getByRole('button', { name: 'Guardar' }).click();
  await expect(page.locator('#root')).toContainText('Terapia DBT');
  await expect(page.locator('#root')).toContainText('Tarifa: $40.000');
});