#!/bin/bash

# Supabase Authentication and RLS Setup Script
# This script helps you set up the authentication system with proper RLS policies

echo "🚀 Setting up Supabase Authentication and RLS Policies"
echo "================================================="

echo ""
echo "📋 Steps to complete the setup:"
echo ""

echo "1. 📁 First, run the SQL policies in your Supabase dashboard:"
echo "   - Go to https://supabase.com/dashboard/project/YOUR_PROJECT_ID/sql"
echo "   - Copy and paste the contents of 'supabase-rls-policies.sql'"
echo "   - Click 'Run' to execute all policies"
echo ""

echo "2. 🪣 Create the required storage buckets:"
echo "   - Go to Storage > Create new bucket"
echo "   - Create bucket named 'product-images' (public: true)"
echo "   - Create bucket named 'profile-images' (public: true)"
echo ""

echo "3. 🔧 Verify your environment variables in .env:"
echo "   - VITE_SUPABASE_URL=your_supabase_url"
echo "   - VITE_SUPABASE_ANON_KEY=your_supabase_anon_key"
echo ""

echo "4. 🧪 Test the authentication flow:"
echo "   - Try logging in as a supplier"
echo "   - Try uploading a product image"
echo "   - Check the browser console for any authentication errors"
echo ""

echo "🔍 Debug Commands:"
echo "=================="
echo ""
echo "If you're still getting 403 errors, run these SQL queries in Supabase SQL editor to debug:"
echo ""
echo "-- Check current user authentication:"
echo "SELECT auth.jwt() ->> 'email' as current_user_email;"
echo ""
echo "-- Check if user exists in database:"
echo "SELECT * FROM usuarios WHERE email = 'your-email@example.com';"
echo ""
echo "-- Check if user is a supplier:"
echo "SELECT u.*, p.id_proveedor FROM usuarios u"
echo "LEFT JOIN proveedores p ON u.id_usuario = p.id_usuario"
echo "WHERE u.email = 'your-email@example.com';"
echo ""
echo "-- Test RLS helper functions:"  
echo "SELECT auth.get_user_db_id();"
echo "SELECT auth.is_supplier();"
echo "SELECT auth.get_supplier_id();"
echo ""

echo "⚠️  Common Issues and Solutions:"
echo "================================"
echo ""
echo "• 403 Unauthorized on image upload:"
echo "  → Make sure the user is registered as a supplier in the 'proveedores' table"
echo "  → Verify storage buckets exist and are public"
echo "  → Check that RLS policies are enabled and correctly configured"
echo ""
echo "• User not found in database:"
echo "  → The AuthSyncService should automatically create users"
echo "  → Check browser console for sync errors"
echo "  → Manually register user roles in signup process"
echo ""
echo "• RLS functions not working:"
echo "  → Make sure all helper functions were created successfully"
echo "  → Check function permissions (SECURITY DEFINER)"
echo "  → Verify JWT token contains email claim"
echo ""

echo "✅ Once setup is complete, your authentication should work with:"
echo "   - Suppliers: CRUD access to their own products/discounts"
echo "   - Customers: Read access to all content + CRUD access to their profile"
echo "   - Proper image upload permissions"
echo "   - Synchronized authentication between Supabase Auth and your database"
echo ""

echo "🆘 If you need help, check the logs in:"
echo "   - Browser Console (F12)"
echo "   - Supabase Dashboard > Logs"
echo "   - Your application's network tab during auth operations"
