export type User = {
  id?: string;
  firstname: string;
  lastname: string;
  forWhom: string;
  nombrePaciente?: string;
  rut?: string;
  password?: string;
  email: string;
  phone?: string;
  address?: string;
  city?: string;
  comuna_id: string | number;
  region?: string;
  country?: string;
  imageUrl?: string;
  created_at?: string;
  token?: string;
  role?: string;
  comunas?: string;
  offers_free_meet_greet?: boolean;
};
