export const routesToExcludeInHeader = [
  '/ingresar',
  '/registrarse',
  '/comenzar',
  '/persona-de-apoyo',
  '/registrar-prestador',
  '/registrar-usuario',
  // '/buscar',
  '/mis-productos',
  '/producto/:id',
  '/proveedor/:id',
  '/cliente/:id',
  '/cambiar-contrasena',
  '/perfil-usuario',
];
