import { DisponibilidadFromFront } from '@/api/disponibilidad/getDisponibilidadByPrestadorId';

export const days: DisponibilidadFromFront[] = [
  {
    id: '0',
    prestadorId: null,
    dayName: 'Lunes',
    startTime: '',
    endTime: '',
    isAvailable: false,
  },
  {
    id: '1',
    prestadorId: null,
    dayName: 'Martes',
    startTime: '',
    endTime: '',
    isAvailable: false,
  },
  {
    id: '2',
    prestadorId: null,
    dayName: 'Miércoles',
    startTime: '',
    endTime: '',
    isAvailable: false,
  },
  {
    id: '3',
    prestadorId: null,
    dayName: 'Jueves',
    startTime: '',
    endTime: '',
    isAvailable: false,
  },
  {
    id: '4',
    prestadorId: null,
    dayName: 'Viernes',
    startTime: '',
    endTime: '',
    isAvailable: false,
  },
  {
    id: '5',
    prestadorId: null,
    dayName: 'Sabado',
    startTime: '',
    endTime: '',
    isAvailable: false,
  },
  {
    id: '6',
    prestadorId: null,
    dayName: 'Domingo',
    startTime: '',
    endTime: '',
    isAvailable: false,
  },
];
