name: Check Codebase

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    environment:
      name: production
      url: https://mercadofiel.cl/

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # See https://github.com/pnpm/action-setup
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

        # See https://github.com/actions/setup-node
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install

        # - name: Create .env.test file
        #   run: |
        #     echo "VITE_ENV=test" >> .env.test
        #     echo "VITE_EMAIL_API_URL=${{ secrets.VITE_EMAIL_API_URL }}" >> .env.test
        #     echo "TRANSACTION_FEE_PERCENTAGE=${{ secrets.TRANSACTION_FEE_PERCENTAGE }}" >> .env.test
        #     echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env.test
        #     echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env.test
        #     echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env.test
        #     echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env.test
        #     echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env.test
        #     echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env.test
        #     echo "VITE_FIREBASE_MEASUREMENT_ID=${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}" >> .env.test
        #   shell: bash

      - name: Build
        run: pnpm run build

    # - name: Unit Tests
    #   run: pnpm run test
    # - name: Install Firebase CLI
    #   run: npm install -g firebase-tools

    # - name: Deploy to Firebase
    #   run: firebase deploy --token "$FIREBASE_TOKEN"
    #   env:
    #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
